#!/bin/bash

rm -f ./settings.txt
echo "0" > ./settings.txt
echo "$4 $5 $6" >> ./settings.txt
../../lemipc $2 1&
../interface/interface_lemipc $2&
for ((i=1;i<$3;i++)); do
    for ((j=0;j<$1;j++)); do
	../../lemipc $2 $((j % $3 + 1))&
    done
done;
